extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:import/recommended
  - plugin:jsx-a11y/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - plugin:jest-dom/recommended
  - eslint-config-prettier
settings:
  import/resolver:
    node:
      extensions: ['.js', '.ts', '.jsx', '.tsx']
      moduleDirectory: ['node_modules', '.']
rules:
  react/react-in-jsx-scope: off
