extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:import/recommended
  - plugin:jsx-a11y/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - plugin:jest-dom/recommended
  - plugin:tailwindcss/recommended
  - plugin:lodash/recommended
  - eslint-config-prettier
plugins:
  - simple-import-sort
settings:
  react:
    version: detect
  import/resolver:
    node:
      extensions: ['.js', '.ts', '.jsx', '.tsx']
      moduleDirectory: ['node_modules', '.']
rules:
  react/react-in-jsx-scope: off
  react/jsx-max-depth:
    - warn
    - max: 10
  react/jsx-sort-props:
    - warn
    - ignoreCase: true
      callbacksLast: true
      shorthandLast: true
      multiline: first
      reservedFirst: true
  react/jsx-no-useless-fragment: warn
  simple-import-sort/imports: warn
  simple-import-sort/exports: warn
  lodash/prefer-lodash-method: off
