extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:import/recommended
  - plugin:jsx-a11y/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - plugin:jest-dom/recommended
  - plugin:tailwindcss/recommended
  - plugin:lodash/recommended
  - plugin:i18next/recommended
  - eslint-config-prettier
settings:
  react:
    version: detect
  import/resolver:
    node:
      extensions: ['.js', '.ts', '.jsx', '.tsx']
      moduleDirectory: ['node_modules', '.']
rules:
  react/react-in-jsx-scope: off
  react/jsx-max-depth:
    - warn
    - max: 10
  react/jsx-sort-props:
    - warn
    - ignoreCase: true
      callbacksLast: true
      shorthandLast: true
      multiline: first
      reservedFirst: true
  react/jsx-no-useless-fragment: warn
  lodash/prefer-lodash-method: off
  import/no-cycle: error
  import/order:
    - warn
    - groups:
        - type
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
      newlines-between: never
      alphabetize:
        order: asc
      warnOnUnassignedImports: true
  '@typescript-eslint/adjacent-overload-signatures': warn
  '@typescript-eslint/consistent-type-imports':
    - warn
    - prefer: type-imports
      fixStyle: inline-type-imports
  i18next/no-literal-string: warn
