export const routes = {
  home: '/',
  welcome: '/welcome',
  login: '/login',
  signup: '/signup',
  forgotPassword: '/forgot-password',
  updatePassword: '/update-password',
  verbs: '/verbs',
  phrases: '/phrases',
  words: '/words',
  category: '/category',
  game: '/game',
  favorites: '/favorites',
  profile: '/profile',
} as const;
